# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HOME(object):
    def setupUi(self, HOME):
        HOME.setObjectName("HOME")
        HOME.resize(1118, 885)
        HOME.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.Hection = QtWidgets.QLabel(HOME)
        self.Hection.setGeometry(QtCore.QRect(420, 260, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Hection.setFont(font)
        self.Hection.setObjectName("Hection")
        self.Logo = QtWidgets.QLabel(HOME)
        self.Logo.setGeometry(QtCore.QRect(440, 0, 271, 251))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("../notsorted/hection scuff.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.Speech = QtWidgets.QPushButton(HOME)
        self.Speech.setGeometry(QtCore.QRect(230, 390, 701, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.Speech.setFont(font)
        self.Speech.setObjectName("Speech")
        self.Debate = QtWidgets.QPushButton(HOME)
        self.Debate.setGeometry(QtCore.QRect(230, 660, 701, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.Debate.setFont(font)
        self.Debate.setObjectName("Debate")
        self.Newscast = QtWidgets.QPushButton(HOME)
        self.Newscast.setGeometry(QtCore.QRect(230, 480, 701, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.Newscast.setFont(font)
        self.Newscast.setObjectName("Newscast")
        self.Storytelling = QtWidgets.QPushButton(HOME)
        self.Storytelling.setGeometry(QtCore.QRect(230, 570, 701, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.Storytelling.setFont(font)
        self.Storytelling.setObjectName("Storytelling")
        self.Hection.raise_()
        self.Speech.raise_()
        self.Debate.raise_()
        self.Newscast.raise_()
        self.Storytelling.raise_()
        self.Logo.raise_()

        self.retranslateUi(HOME)
        QtCore.QMetaObject.connectSlotsByName(HOME)

    def retranslateUi(self, HOME):
        _translate = QtCore.QCoreApplication.translate
        HOME.setWindowTitle(_translate("HOME", "Form"))
        self.Hection.setText(_translate("HOME", "HECTION 9.0"))
        self.Speech.setText(_translate("HOME", "Speech Competition Registration"))
        self.Debate.setText(_translate("HOME", "Debate Competition Registration"))
        self.Newscast.setText(_translate("HOME", "Newscast Competition Registration"))
        self.Storytelling.setText(_translate("HOME", "Storytelling Competition Registration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HOME = QtWidgets.QWidget()
    ui = Ui_HOME()
    ui.setupUi(HOME)
    HOME.show()
    sys.exit(app.exec_())
