# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'speech.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_SPEECH(object):
    def koneksi(self):
        con = pymysql.connect(host="localhost", user="root", password="", db="hection", port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")
            
    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def save(self):
        name = self.plainTextEdit.toPlainText()
        hsname = self.plainTextEdit_2.toPlainText()
        hsaddress = self.plainTextEdit_3.toPlainText()
        wa = self.plainTextEdit_4.toPlainText()
        email = self.plainTextEdit_5.toPlainText()
        instagram = self.plainTextEdit_6.toPlainText()
        insert = (name, hsname, hsaddress, wa, email, instagram)
        print(insert)
        con = pymysql.connect(host="localhost", user="root", password="", db="hection", port=3306, autocommit=True)
        cur = con.cursor()
        sql = "INSERT INTO hection(name, hs_name, hs_address, wa, email, ig) + VALUES " + str(insert)
        data = cur.execute(sql)
        if(data):
            self.messagebox("SUKSES", "Data Tersimpan")
        else:
            self.messagebox("GAGAL", "Data Gagal Tersimpan")

    def clear(self):
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_5.setPlainText("")
        self.plainTextEdit_6.setPlainText("")
    
    
    def setupUi(self, SPEECH):
        self.koneksi()
        SPEECH.setObjectName("SPEECH")
        SPEECH.resize(1118, 885)
        SPEECH.setStyleSheet("background-color: rgb(166, 232, 240);")
        self.label = QtWidgets.QLabel(SPEECH)
        self.label.setGeometry(QtCore.QRect(310, 10, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SPEECH)
        self.label_2.setGeometry(QtCore.QRect(60, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SPEECH)
        self.label_3.setGeometry(QtCore.QRect(60, 310, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(SPEECH)
        self.label_4.setGeometry(QtCore.QRect(60, 390, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(SPEECH)
        self.label_5.setGeometry(QtCore.QRect(60, 470, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(SPEECH)
        self.label_6.setGeometry(QtCore.QRect(60, 550, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(SPEECH)
        self.label_7.setGeometry(QtCore.QRect(60, 630, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        
        self.plainTextEdit = QtWidgets.QPlainTextEdit(SPEECH)
        self.plainTextEdit.setGeometry(QtCore.QRect(370, 220, 671, 41))
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(SPEECH)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(370, 300, 671, 41))
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(SPEECH)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(370, 380, 671, 41))
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(SPEECH)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(370, 460, 671, 41))
        self.plainTextEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(SPEECH)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(370, 540, 671, 41))
        self.plainTextEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(SPEECH)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(370, 620, 671, 41))
        self.plainTextEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        
        self.Clear = QtWidgets.QPushButton(SPEECH)
        self.Clear.setGeometry(QtCore.QRect(930, 730, 112, 34))
        self.Clear.setObjectName("Clear")
        self.Clear.clicked.connect(self.clear)
        
        self.Save = QtWidgets.QPushButton(SPEECH)
        self.Save.setGeometry(QtCore.QRect(710, 730, 112, 34))
        self.Save.setObjectName("Save")
        self.Save.clicked.connect(self.save)

        
        
        self.label_8 = QtWidgets.QLabel(SPEECH)
        self.label_8.setGeometry(QtCore.QRect(60, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")

        self.retranslateUi(SPEECH)
        QtCore.QMetaObject.connectSlotsByName(SPEECH)
    

    def retranslateUi(self, SPEECH):
        _translate = QtCore.QCoreApplication.translate
        SPEECH.setWindowTitle(_translate("SPEECH", "Form"))
        self.label.setText(_translate("SPEECH", "HECTION 9.0 Registration Form"))
        self.label_2.setText(_translate("SPEECH", "Full Name"))
        self.label_3.setText(_translate("SPEECH", "Name of Highschool"))
        self.label_4.setText(_translate("SPEECH", "High School Address"))
        self.label_5.setText(_translate("SPEECH", "Phone Number of WhatsApp"))
        self.label_6.setText(_translate("SPEECH", "Email Address"))
        self.label_7.setText(_translate("SPEECH", "Instagram"))
        self.Clear.setText(_translate("SPEECH", "Clear"))
        self.Save.setText(_translate("SPEECH", "Save"))
        self.label_8.setText(_translate("SPEECH", "SPEECH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SPEECH = QtWidgets.QWidget()
    ui = Ui_SPEECH()
    ui.setupUi(SPEECH)
    SPEECH.show()
    sys.exit(app.exec_())
